kullanici=input("Kullanici adinizi giriniz:")
dosya=open("log.txt","a")
dosya.write(f"{kullanici} sisteme giris yapti")
dosya.close
dosya=open( "log.txt","r")
icerik=dosya.read()
print(icerik)
dosya.close()
print("Log kaydi olusturuldu.")
dosya=open("log.txt","w")
dosya.write("Yeni veri")
dosya.close()
